backend:
  name: github
  repo: timplay33/Wiki-Create-Mobile-Packages
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "users"
    label: "users"
    folder: "/users"
    create: true
    slug: "{{path}}/{{slug}}"
    path: "{{path}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Path", name: "path", widget: "string", hint: "Specify the subfolder path (e.g., 'guides' or 'tutorials/basics')", default: ""}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "developers"
    label: "developers"
    folder: "/developers"
    create: true
    slug: "{{path}}/{{slug}}"
    path: "{{path}}/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Path", name: "path", widget: "string", hint: "Specify the subfolder path (e.g., 'api' or 'guides/advanced')", default: ""}
      - {label: "Body", name: "body", widget: "markdown"}